#!/usr/bin/env bash

MOUNT_DIR=$HOME/GoogleDrive/
MOUNTED=$(mountpoint $MOUNT_DIR)

case $MOUNTED in
    "$MOUNT_DIR is not a mountpoint")
        rclone mount google_drive: $MOUNT_DIR &
        ;;

    "$MOUNT_DIR is a mountpoint")
        umount $MOUNT_DIR
        ;;
esac
